//
// Created by mark- on 06/09/2020.
//

#ifndef VCRITTERS_SRC_GAME_ENTITIES_BASEBUILDING_H_
#define VCRITTERS_SRC_GAME_ENTITIES_BASEBUILDING_H_

#endif //VCRITTERS_SRC_GAME_ENTITIES_BASEBUILDING_H_
